AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for docker-app
Globals:
  Function:
    Timeout: 3

Resources:
  BucketReceivePyvipsv1S3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: bucket-receive-pyvipsv1
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${BucketReceivePyvipsv1}/*'
            Principal: '*'
  BucketReceivePyvipsv1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-receive-pyvipsv1

  BucketStorePyvipsv1S3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: bucket-store-pyvipsv1
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${BucketStorePyvipsv1}/*'
            Principal: '*'
  BucketStorePyvipsv1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-store-pyvipsv1

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt DockerPyvipsFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt BucketReceivePyvipsv1.Arn
  DockerPyvipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: bucket-receive-pyvipsv1
        - S3WritePolicy:
            BucketName: bucket-store-pyvipsv1
      Events:
        FileUpload:
          Type: S3
          Properties: 
            Bucket: !Ref BucketReceivePyvipsv1
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.9-v1

Outputs:
  DockerPyvipsFunction:
    Description: "Docker Lambda Function ARN"
    Value: !GetAtt DockerPyvipsFunction.Arn
  DockerPyvipsFunctionIamRole:
    Description: "Implicit IAM Role created for Docker function"
    Value: !GetAtt DockerPyvipsFunctionRole.Arn
